services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    # Execute Gunicorn for production instead of python manage.py runserver
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    restart: always
